### ISSUE TITLE
performance on coco?

### ISSUE THREAD

**Issue by Jarr0d** [poodarchu/learn_aug_for_object_detection.numpy#1]
Hi poodarchu,
Great job! I'm also trying to do the same thing but trapped at TranslateY_Only_BBoxes func. Hope I can get some hints from your job.
BTW, have you tested the performance by using policy_v0 (the same as paper)?

**Comment by poodarchu** [comment]
very baddly. about mAP 10.5%;  I think some augmentation hurt the detector dramatically.

glad to receive your feedback.

**Comment by poodarchu** [comment]
Reasonable.

**Comment by 1224wxwx** [comment]
So, according to your "read me", it seems that those augmentation don't work?

**Comment by poodarchu** [comment]
> So, according to your "read me", it seems that those augmentation don't work?

Yes, many of google's recent work doesn't work at all.
