### ISSUE TITLE
A  bug    In  func : _shear_bbox  

### ISSUE THREAD

**Issue by heartInsert** [poodarchu/learn_aug_for_object_detection.numpy#2]
In   function  ` shear_with_bboxes=> _shear_bbox`  :  your  return  3  additional   values  ` bbox[4], bbox[5], bbox[6]`   compare  to  the  orignal   tesorflow_version     line  1029,
`  return tf.stack([min_y, min_x, max_y, max_x])`

Question 1: in  the   orignal   tesorflow_version , bboxes  input  format  should   [ymin,xmin,ymax,xmax],there is no bbox[5]  and  bbox[6],   do  you  change  the  input  format  in  numpy_version ?
Questin  2:  I  saw  a   new  policy  named  `policy_custom`, will   it   worked  better  than  others  ?
The  policy   which  I  used   is  `policy_custom`, bboxes  format  is `[ymin,xmin,ymax,xmax]`.
Thanks  for your reply

**Comment by poodarchu** [comment]
1. my dataloader need extra 3 values for a bbox, you can remove that.
2. default policies are so strong that they'll cause performance decrease greatly. so I add a light augmentation version, it still doesn't work, but only with less performance decrease compared to original policies.
