### ISSUE TITLE
A new bug in Google Code

### ISSUE THREAD

**Issue by xingyuanbu** [poodarchu/learn_aug_for_object_detection.numpy#3]
https://github.com/tensorflow/tpu/blob/master/models/official/detection/utils/autoaugment_utils.py#L686
https://github.com/poodarchu/learn_aug_for_object_detection.numpy/blob/master/autoaugment_utils.py#L657

I think I've found another bug for Google AutoAug seen above link, which augments an image as many time as the number of bboxes in it.
Assuming we augment the bboxes and images by random flipping, in this case, each bbox is flipped by a probability P, but the image will be flip many times and the probability is not equal to P.

BTW, can you post the experiment results for further discussion?

**Comment by poodarchu** [comment]
1x fpn -2.5%
